name: Lint Check

on:
  pull_request:
    branches: [ main ]

jobs:
  run-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: use Node.js 18
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: install dependencies
        run: npm install
      - name: run lint
        run: npm run lint
